### ISSUE TITLE
Exception when published to CF

### ISSUE THREAD

**Issue by inguyendo** [OultimoCoder/cloudflare-planetscale-hono-boilerplate#11]
Just showing log:

"exceptions": [
    {
      "name": "Error",
      "message": "ZodError",
      "timestamp": 1683176727739
    }

Without any info

**Comment by tokenhousetopdev** [comment]
Ahh sorry. I haven't updated this yet but fixed it in my personal projects. The issue will be to do with parsing the configuration on launch. I need to coerce the types with zod for it to work correctly.

**Comment by OultimoCoder** [comment]
If you make sure every ENV variable is set and secret is published this will be fixed in https://github.com/OultimoCoder/cloudflare-planetscale-hono-boilerplate/releases/tag/v1.1.0
