### ISSUE TITLE
miniflare command not found

### ISSUE THREAD

**Issue by devnomic** [OultimoCoder/cloudflare-planetscale-hono-boilerplate#13]
when run`npm run dev` the console show
```
sh: miniflare: command not found
```

it seems the miniflare cli has been discontinued in v3.

**Comment by OultimoCoder** [comment]
I missed that! You can downgrade to 2 in the meantime but I'll fix this in the next update.

**Comment by OultimoCoder** [comment]
Fixed in https://github.com/OultimoCoder/cloudflare-planetscale-hono-boilerplate/releases/tag/v1.2.0
