### ISSUE TITLE
example env

### ISSUE THREAD

**Issue by devnomic** [OultimoCoder/cloudflare-planetscale-hono-boilerplate#14]
it would be better if we have `.env.example` file as starting point to see which env variable is used in the app.

Right now it throws error if there is no .env or insufficient env variable.

**Comment by OultimoCoder** [comment]
Ahh thanks for pointing that out, yeah `.env.test` and `.env.dev` are required for testing and running locally, I'll update docs and add to the readme.

**Comment by devnomic** [comment]
Thank you,
Also it seems based on scripts/migrate.ts

.env is for dev
.env.prod is for prod

I think it would be better .env is for prod
.env.dev is for dev

**Comment by OultimoCoder** [comment]
Fixed in https://github.com/OultimoCoder/cloudflare-planetscale-hono-boilerplate/releases/tag/v1.2.0
