### ISSUE TITLE
the nmp test:*  scripts dont run anymore since you removed "cross-env" from your last commit

### ISSUE THREAD

**Issue by alexdoan102** [OultimoCoder/cloudflare-planetscale-hono-boilerplate#4]
![image](https://user-images.githubusercontent.com/73307/222536790-0a433d39-01d9-4c54-9238-37c3b4a26c21.png)

**Comment by OultimoCoder** [comment]
Sorry for this!

Now fixed by: https://github.com/OultimoCoder/cloudflare-planetscale-hono-boilerplate/releases/tag/v1.0.7
